### PR TITLE
azure-pipelines: rework

### PR DESCRIPTION
**Pull request by dawidd6**
This is a rework of Azure pipelines config.
Major changes:
- run on `homebrew/brew` Docker image
- swap `if` bash condition with Azure condition
- copy checked out repo to Taps directory
- don't run `test-bot`, seemed redundant to me
- delete unused env variables
- reword `displayName`s
- update Homebrew itself before running `brew style`

### CODE REVIEW

**Comment by dawidd6** [comment]
Still the same issue as here: https://github.com/Homebrew/homebrew-linux-dev/pull/127

```
Error: failed to run `/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/shims/scm/bundle install`!
```

**Comment by sjackman** [comment]
Do you have the time and inclination to fix that error? A total rewrite makes me uncomfortable unless we can verify that CI is working.

**Comment by sjackman** [comment]
Alternatively, do you have any interest in porting this to GitHub Actions CI?

**Comment by dawidd6** [comment]
I can do that. Shouldn't take long.

**Comment by dawidd6** [comment]
I think I have to do this directly on `master` as the workflow does not seem to be detected.

**Comment by sjackman** [comment]
Great! Try it using a PR from a branch in this repo rather than a fork PR.

**Comment by dawidd6** [comment]
Closing in favor of: https://github.com/Homebrew/homebrew-linux-dev/pull/129

**Pull request closed without merging**
