### PR TITLE
build-bottle-pr: fix --force option detection

### PR DESCRIPTION
**Pull request by dawidd6**
https://github.com/Homebrew/brew/pull/6939

### CODE REVIEW

**Comment by issyl0** [comment]
I feel like we should keep up with the trends and should switch `ARGV` to `Homebrew.args` in all the right places. But that's a much larger piece of work.

**Comment by dawidd6** [comment]
To be honest I don't get how this new `Homebrew.args` thing work. Would happily transition our scripts  though.

**Comment by issyl0** [comment]
I was planning to have a look this weekend. 👩‍💻 But I was also planning to go to the gym. 🏋️‍♀️ But maybe I'll do none of these things - like last weekend where I mostly 🛌.

**Comment by dawidd6** [comment]
Merging this for now.

**Comment by issyl0** [comment]
Oh, yeah, I didn't mean for my comment to block merging!

**Pull request merged**
