### PR TITLE
Remove Azure pipelines config

### PR DESCRIPTION
**Pull request by dawidd6**
Need to remove the Azure config to finalize the switch to GH Actions.

### CODE REVIEW

**Comment by sjackman** [comment]
I've invited you the Linuxbrew org on Azure.

**Comment by issyl0** [comment]
This will also need a repo admin to disable the "required status check" in the Settings for this repo.

**Comment by issyl0** [comment]
Closing and re-opening won't help. :trollface:

**Comment by dawidd6** [comment]
Imma do it again.

**Pull request merged**
