### PR TITLE
Switch from using ARGV to Homebrew.args

### PR DESCRIPTION
**Pull request by issyl0**
- Homebrew is gradually switching to its own argument parser rather than using ARGV: https://github.com/Homebrew/brew/issues/5730
- This is still a work in progress as there are a lot of scripts here!

### CODE REVIEW

**Comment by issyl0** [comment]
I've tested `check-for-upstream-core-formulae`, `build-bottle-pr`, `merge-homebrew`, `announce`, `find-formulae-to-bottle` and `find-not-bottled`. Even so, I probably haven't tested them with all their options as they didn't apply to my usage (the best way to test something is to use it, right?). Hence I'm going to leave this open for a few days and request that maintainers use this branch to do day-to-day stuff, so we can deal with any issues. 😍

**Comment by dawidd6** [comment]
First thing. There does not seem to be a way to get a help message out of the scripts, which is weird:

```
➜  ~  brew build-bottle-pr --help
Warning: No help text in: /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-linux-dev/cmd/brew-build-bottle-pr.rb
Example usage:
  brew search [TEXT|/REGEX/]
  brew info [FORMULA...]
  brew install FORMULA...
  brew update
  brew upgrade [FORMULA...]
  brew uninstall FORMULA...
  brew list [FORMULA...]

Troubleshooting:
  brew config
  brew doctor
  brew install --verbose --debug FORMULA

Contributing:
  brew create [URL [--no-fetch]]
  brew edit [FORMULA...]

Further help:
  brew commands
  brew help [COMMAND]
  man brew
  https://docs.brew.sh
➜  ~  brew build-bottle-pr -h
Warning: No help text in: /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-linux-dev/cmd/brew-build-bottle-pr.rb
Example usage:
  brew search [TEXT|/REGEX/]
  brew info [FORMULA...]
  brew install FORMULA...
  brew update
  brew upgrade [FORMULA...]
  brew uninstall FORMULA...
  brew list [FORMULA...]

Troubleshooting:
  brew config
  brew doctor
  brew install --verbose --debug FORMULA

Contributing:
  brew create [URL [--no-fetch]]
  brew edit [FORMULA...]

Further help:
  brew commands
  brew help [COMMAND]
  man brew
  https://docs.brew.sh
➜  ~  brew help build-bottle-pr
Warning: No help text in: /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-linux-dev/cmd/brew-build-bottle-pr.rb
Example usage:
  brew search [TEXT|/REGEX/]
  brew info [FORMULA...]
  brew install FORMULA...
  brew update
  brew upgrade [FORMULA...]
  brew uninstall FORMULA...
  brew list [FORMULA...]

Troubleshooting:
  brew config
  brew doctor
  brew install --verbose --debug FORMULA

Contributing:
  brew create [URL [--no-fetch]]
  brew edit [FORMULA...]

Further help:
  brew commands
  brew help [COMMAND]
  man brew
  https://docs.brew.sh
```

**Comment by jonchang** [comment]
> First thing. There does not seem to be a way to get a help message out of the scripts, which is weird:

I just switched to this branch and it seems to work fine for me:

```console
% brew announce --help
Usage: brew announce formulae:
  Create an announcement for new formulae.
% brew build-bottle-pr --help
Usage: brew build-bottle-pr [--remote=user] [--dry-run] [--verbose]
[--tap-dir] [--force]:
  Submit a pull request to build a bottle for a formula.

  If --remote is passed, use the specified GitHub remote. Otherwise, use
origin.
  If --dry-run is passed, do not actually make any PR's.
  If --verbose is passed, print extra information.
  If --tap-dir is passed, use the specified full path to a tap. Otherwise, use
the Homebrew on Linux standard install location.
  If --force is passed, delete local and remote 'bottle-name' branches if
they exist. Use with care.
  If --browse is passed, open a web browser for the new pull request.
% brew check-for-deleted-upstream-core-formulae --help
Usage: brew check-for-deleted-upstream-core-formulae [--homebrew-repo-dir]
[--linuxbrew-repo-dir]:
  Outputs a list of formulae (with .rb suffix) for further git rm usage.

  If no arguments are passed, use master branch of core tap as
Homebrew/linuxbrew-core repo and homebrew/master branch as
Homebrew/homebrew-core repo.
  If --linuxbrew-repo-dir is passed, use the specified full path to the
Homebrew/linuxbrew-core repo. Otherwise, use the Homebrew on Linux standard
install location.
  When --homebrew-repo-dir is passed, use the specified full path to the
Homebrew/homebrew-core repo. Otherwise, use the Homebrew on Linux standard
install location.
```

**Comment by dawidd6** [comment]
You still seem to have the old version somehow.

Commenting this line out: https://github.com/Homebrew/brew/blob/d014d5a982bc3712179af59faae33fe777d49aef/Library/Homebrew/brew.rb#L97 resolves the issue for me.

**Comment by jonchang** [comment]
Interesting. Do you have an alias or something that is changing the call to `brew`? Commenting out that line gives me:

```console
% brew build-bottle-pr --help
Error: No remote has been specified: use `--remote=origin` or `--remote=$HOMEBREW_GITHUB_USER`
```

**Comment by dawidd6** [comment]
Nope. No alias:

```
➜  ~  type brew
brew is /home/linuxbrew/.linuxbrew/bin/brew
```

**Comment by jonchang** [comment]
Ok, it's a macOS/Linux difference. It works on macOS but not on Linux for some reason.

**Comment by jonchang** [comment]
Scratch that, my mistake. I had the old `linuxbrew/developer` tapped. I can now repro the help text issue.

**Comment by dawidd6** [comment]
Possible patch for `brew` to fix it:

```diff
diff --git a/Library/Homebrew/brew.rb b/Library/Homebrew/brew.rb
index 11dd3ff30..89b8e906e 100644
--- a/Library/Homebrew/brew.rb
+++ b/Library/Homebrew/brew.rb
@@ -94,7 +94,7 @@ begin
   # - if cmd is Cask, let Cask handle the help command instead
   if (empty_argv || help_flag) && cmd != "cask"
     require "help"
-    Homebrew::Help.help cmd, empty_argv: empty_argv
+    Homebrew::Help.help cmd, empty_argv: empty_argv, internal_cmd: internal_cmd
     # `Homebrew.help` never returns, except for external/unknown commands.
   end
 
diff --git a/Library/Homebrew/help.rb b/Library/Homebrew/help.rb
index c99e6dae7..4092eb91c 100644
--- a/Library/Homebrew/help.rb
+++ b/Library/Homebrew/help.rb
@@ -72,6 +72,9 @@ module Homebrew
       # Resume execution in `brew.rb` for unknown commands.
       return if path.nil?
 
+      # Resume execution in `brew.rb` for external commands using cli/parser.
+      return unless flags[:internal_cmd]
+
       # Display help for internal command (or generic help if undocumented).
       puts command_help(path)
       exit 0

```

Though I'm not sure if it is the right approach.

**Comment by jonchang** [comment]
I think teaching `command_help` to deal with new options parser style help would be the more correct approach, since that is what is done for internal commands as well.

**Comment by issyl0** [comment]
It had better work eventually - I spent ages copy/paste/reword those `usage_banner` sections. :laughing: Good spot, and thanks for the reproduction! :eyes:

**Comment by jonchang** [comment]
> I think teaching `command_help` to deal with new options parser style help would be the more correct approach, since that is what is done for internal commands as well.

I take that back -- I actually can't tell what is calling the help text for external commands. Your solution seems to work but I don't really understand why.

**Comment by dawidd6** [comment]
Another thing is that, `switch` must end with `?`. For example `Homebrew.args.verbose` must become `Homebrew.args.verbose?` and `Homebrew.args.force` -> `Homebrew.args.force?`.

**Comment by issyl0** [comment]
Argh. How did I not notice these? Thanks, @dawidd6!

**Comment by issyl0** [comment]
Do we think - thanks to the excellent testing by Dawid - that this is good to merge now? :heart:

**Comment by dawidd6** [comment]
Nooo, we still need to fix `-h | --help` for external commands using `cli/parser` in `brew` first.

**Comment by issyl0** [comment]
The `--help` continues to work if we keep the `#:` comment lines at the top. The code for that seems to be [in help.rb](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/help.rb#L93-L95), which calls [utils.rb](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/utils.rb#L500-L502), which itself `grep`s for `#:`. This only happens for external commands, as `brew bump-formula-pr` works fine and has only the Homebrew::CLI::Parser `usage_banner` etc.

**Comment by dawidd6** [comment]
Maybe we could check for `require 'cli/parser'` string and if it is present, don't look for `#:` lines?

**Pull request merged**
